INSERT INTO TICKER_MAP(ID, TICKER_CD, TICKER_DESC) VALUES(1, 'SAVE', 'Nordnet');
INSERT INTO TICKER_MAP(ID, TICKER_CD, TICKER_DESC) VALUES(2, 'GME', 'GameStop');
INSERT INTO TICKER_MAP(ID, TICKER_CD, TICKER_DESC) VALUES(3, 'TSLA', 'Tesla');